// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MatthiasToolbox.Test
{
    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BaseAccessor
    {

        protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;

        protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type)
        {
            m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
        }

        protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) :
            this(null, type)
        {
        }

        internal virtual object Target
        {
            get
            {
                return m_privateObject.Target;
            }
        }

        public override string ToString()
        {
            return this.Target.ToString();
        }

        public override bool Equals(object obj)
        {
            if (typeof(BaseAccessor).IsInstanceOfType(obj))
            {
                obj = ((BaseAccessor)(obj)).Target;
            }
            return this.Target.Equals(obj);
        }

        public override int GetHashCode()
        {
            return this.Target.GetHashCode();
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_Adler32Accessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Cryptography.Checksums.Adler32));

        internal BlueLogic_SDelta_Core_Adler32Accessor(global::MatthiasToolbox.Cryptography.Checksums.Adler32 target)
            :
                base(target, m_privateType)
        {
        }

        internal static ulong A32_BASE
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("A32_BASE")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("A32_BASE", value);
            }
        }

        internal static int A32_NMAX
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("A32_NMAX")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("A32_NMAX", value);
            }
        }

        internal static ulong s1
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("s1")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("s1", value);
            }
        }

        internal static ulong s2
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("s2")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("s2", value);
            }
        }

        internal static void A32_DO1(uint[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO1", new System.Type[] {
                    typeof(uint).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO2(uint[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO2", new System.Type[] {
                    typeof(uint).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO4(uint[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO4", new System.Type[] {
                    typeof(uint).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO8(uint[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO8", new System.Type[] {
                    typeof(uint).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO16(uint[] buf, int start)
        {
            object[] args = new object[] {
                buf,
                start};
            m_privateType.InvokeStatic("A32_DO16", new System.Type[] {
                    typeof(uint).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO1(byte[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO1", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO2(byte[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO2", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO4(byte[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO4", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO8(byte[] buf, int i)
        {
            object[] args = new object[] {
                buf,
                i};
            m_privateType.InvokeStatic("A32_DO8", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int)}, args);
        }

        internal static void A32_DO16(byte[] buf, int start)
        {
            object[] args = new object[] {
                buf,
                start};
            m_privateType.InvokeStatic("A32_DO16", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int)}, args);
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_MD4Accessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Cryptography.Hashes.MD4));

        internal BlueLogic_SDelta_Core_MD4Accessor(global::MatthiasToolbox.Cryptography.Hashes.MD4 target)
            :
                base(target, m_privateType)
        {
        }

        internal static int BLOCK_LENGTH
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("BLOCK_LENGTH")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("BLOCK_LENGTH", value);
            }
        }

        internal uint[] context
        {
            get
            {
                uint[] ret = ((uint[])(m_privateObject.GetField("context")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("context", value);
            }
        }

        internal long count
        {
            get
            {
                long ret = ((long)(m_privateObject.GetField("count")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("count", value);
            }
        }

        internal byte[] buffer
        {
            get
            {
                byte[] ret = ((byte[])(m_privateObject.GetField("buffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("buffer", value);
            }
        }

        internal uint[] X
        {
            get
            {
                uint[] ret = ((uint[])(m_privateObject.GetField("X")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("X", value);
            }
        }

        internal static global::MatthiasToolbox.Cryptography.Hashes.MD4 CreatePrivate(global::MatthiasToolbox.Cryptography.Hashes.MD4 md)
        {
            object[] args = new object[] {
                md};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(typeof(global::MatthiasToolbox.Cryptography.Hashes.MD4), new System.Type[] {
                    typeof(global::MatthiasToolbox.Cryptography.Hashes.MD4)}, args);
            return ((global::MatthiasToolbox.Cryptography.Hashes.MD4)(priv_obj.Target));
        }

        internal void engineReset()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("engineReset", new System.Type[0], args);
        }

        internal void engineUpdate(byte b)
        {
            object[] args = new object[] {
                b};
            m_privateObject.Invoke("engineUpdate", new System.Type[] {
                    typeof(byte)}, args);
        }

        internal void engineUpdate(byte[] input, int offset, int len)
        {
            object[] args = new object[] {
                input,
                offset,
                len};
            m_privateObject.Invoke("engineUpdate", new System.Type[] {
                    typeof(byte).MakeArrayType(),
                    typeof(int),
                    typeof(int)}, args);
        }

        internal byte[] engineDigest()
        {
            object[] args = new object[0];
            byte[] ret = ((byte[])(m_privateObject.Invoke("engineDigest", new System.Type[0], args)));
            return ret;
        }

        internal void transform(ref byte[] block, int offset)
        {
            object[] args = new object[] {
                block,
                offset};
            m_privateObject.Invoke("transform", new System.Type[] {
                    typeof(byte).MakeArrayType().MakeByRefType(),
                    typeof(int)}, args);
            block = ((byte[])(args[0]));
        }

        internal uint FF(uint a, uint b, uint c, uint d, uint x, int s)
        {
            object[] args = new object[] {
                a,
                b,
                c,
                d,
                x,
                s};
            uint ret = ((uint)(m_privateObject.Invoke("FF", new System.Type[] {
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(int)}, args)));
            return ret;
        }

        internal uint GG(uint a, uint b, uint c, uint d, uint x, int s)
        {
            object[] args = new object[] {
                a,
                b,
                c,
                d,
                x,
                s};
            uint ret = ((uint)(m_privateObject.Invoke("GG", new System.Type[] {
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(int)}, args)));
            return ret;
        }

        internal uint HH(uint a, uint b, uint c, uint d, uint x, int s)
        {
            object[] args = new object[] {
                a,
                b,
                c,
                d,
                x,
                s};
            uint ret = ((uint)(m_privateObject.Invoke("HH", new System.Type[] {
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(uint),
                    typeof(int)}, args)));
            return ret;
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_ScriptDrawerAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Delta.Utilities.ScriptDrawer));

        internal BlueLogic_SDelta_Core_ScriptDrawerAccessor(global::MatthiasToolbox.Delta.Utilities.ScriptDrawer target)
            :
                base(target, m_privateType)
        {
        }

        internal global::System.Drawing.Bitmap bmp
        {
            get
            {
                global::System.Drawing.Bitmap ret = ((global::System.Drawing.Bitmap)(m_privateObject.GetField("bmp")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("bmp", value);
            }
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor fdraw
        {
            get
            {
                object _ret_val = m_privateObject.GetField("fdraw");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor ret = _ret;
                return ret;
            }
            set
            {
                m_privateObject.SetField("fdraw", value);
            }
        }

        internal int lenA
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("lenA")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("lenA", value);
            }
        }

        internal int lenB
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("lenB")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("lenB", value);
            }
        }

        internal global::System.Windows.Forms.PictureBox pic
        {
            get
            {
                global::System.Windows.Forms.PictureBox ret = ((global::System.Windows.Forms.PictureBox)(m_privateObject.GetField("pic")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("pic", value);
            }
        }

        internal float scale
        {
            get
            {
                float ret = ((float)(m_privateObject.GetField("scale")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("scale", value);
            }
        }

        internal string sX
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("sX")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("sX", value);
            }
        }

        internal string sY
        {
            get
            {
                string ret = ((string)(m_privateObject.GetField("sY")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("sY", value);
            }
        }

        internal int offX
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("offX")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("offX", value);
            }
        }

        internal int offY
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("offY")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("offY", value);
            }
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor fd
        {
            get
            {
                object _ret_val = m_privateObject.GetField("fd");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor ret = _ret;
                return ret;
            }
            set
            {
                m_privateObject.SetField("fd", value);
            }
        }

        internal void DrawMain()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("DrawMain", new System.Type[0], args);
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw");

        internal BlueLogic_SDelta_Core_TextDelta_FormsDrawAccessor(object target) :
            base(target, m_privateType)
        {
        }

        internal global::System.Drawing.Graphics G
        {
            get
            {
                global::System.Drawing.Graphics ret = ((global::System.Drawing.Graphics)(m_privateObject.GetField("G")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("G", value);
            }
        }

        internal global::System.Drawing.Color myBackColor
        {
            get
            {
                global::System.Drawing.Color ret = ((global::System.Drawing.Color)(m_privateObject.GetField("myBackColor")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("myBackColor", value);
            }
        }

        internal global::System.Drawing.Color myLastColor
        {
            get
            {
                global::System.Drawing.Color ret = ((global::System.Drawing.Color)(m_privateObject.GetField("myLastColor")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("myLastColor", value);
            }
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor myMode
        {
            get
            {
                object _ret_val = m_privateObject.GetField("myMode");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor ret = _ret;
                return ret;
            }
            set
            {
                m_privateObject.SetField("myMode", value);
            }
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor myBounds
        {
            get
            {
                object _ret_val = m_privateObject.GetField("myBounds");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor ret = _ret;
                return ret;
            }
            set
            {
                m_privateObject.SetField("myBounds", value);
            }
        }

        internal global::System.Drawing.Color BackColor
        {
            get
            {
                global::System.Drawing.Color ret = ((global::System.Drawing.Color)(m_privateObject.GetProperty("BackColor")));
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("BackColor", value);
            }
        }

        internal global::System.Drawing.Color LastColor
        {
            get
            {
                global::System.Drawing.Color ret = ((global::System.Drawing.Color)(m_privateObject.GetProperty("LastColor")));
                return ret;
            }
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor Mode
        {
            get
            {
                object _ret_val = m_privateObject.GetProperty("Mode");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor ret = _ret;
                return ret;
            }
            set
            {
                m_privateObject.SetProperty("Mode", value);
            }
        }

        internal global::System.Drawing.Bitmap myImage
        {
            get
            {
                global::System.Drawing.Bitmap ret = ((global::System.Drawing.Bitmap)(m_privateObject.GetField("myImage")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("myImage", value);
            }
        }

        internal static object CreatePrivate(global::System.Drawing.Bitmap img)
        {
            object[] args = new object[] {
                img};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw", new System.Type[] {
                    typeof(global::System.Drawing.Bitmap)}, args);
            return priv_obj.Target;
        }

        internal static object CreatePrivate(global::System.Windows.Forms.Form Window)
        {
            object[] args = new object[] {
                Window};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw", new System.Type[] {
                    typeof(global::System.Windows.Forms.Form)}, args);
            return priv_obj.Target;
        }

        internal static object CreatePrivate(global::System.Windows.Forms.Control Window)
        {
            object[] args = new object[] {
                Window};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw", new System.Type[] {
                    typeof(global::System.Windows.Forms.Control)}, args);
            return priv_obj.Target;
        }

        internal static object CreatePrivate(global::System.IntPtr Handle, global::System.Drawing.Rectangle Bounds)
        {
            object[] args = new object[] {
                Handle,
                Bounds};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw", new System.Type[] {
                    typeof(global::System.IntPtr),
                    typeof(global::System.Drawing.Rectangle)}, args);
            return priv_obj.Target;
        }

        internal static object CreatePrivate(global::System.IntPtr Handle, int xMin, int yMin, int xMax, int yMax)
        {
            object[] args = new object[] {
                Handle,
                xMin,
                yMin,
                xMax,
                yMax};
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw", new System.Type[] {
                    typeof(global::System.IntPtr),
                    typeof(int),
                    typeof(int),
                    typeof(int),
                    typeof(int)}, args);
            return priv_obj.Target;
        }

        internal void Dispose()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("Dispose", new System.Type[0], args);
        }

        internal global::System.Drawing.PointF Transform(float x, float y)
        {
            object[] args = new object[] {
                x,
                y};
            global::System.Drawing.PointF ret = ((global::System.Drawing.PointF)(m_privateObject.Invoke("Transform", new System.Type[] {
                    typeof(float),
                    typeof(float)}, args)));
            return ret;
        }

        internal void TransformRef(ref global::System.Drawing.PointF p)
        {
            object[] args = new object[] {
                p};
            m_privateObject.Invoke("TransformRef", new System.Type[] {
                    typeof(global::System.Drawing.PointF).MakeByRefType()}, args);
            p = ((global::System.Drawing.PointF)(args[0]));
        }

        internal void TransformRef(ref float x, ref float y)
        {
            object[] args = new object[] {
                x,
                y};
            m_privateObject.Invoke("TransformRef", new System.Type[] {
                    typeof(float).MakeByRefType(),
                    typeof(float).MakeByRefType()}, args);
            x = ((float)(args[0]));
            y = ((float)(args[1]));
        }

        internal void Clear()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("Clear", new System.Type[0], args);
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Line(global::System.Drawing.Color c, int w, global::System.Drawing.PointF p1, global::System.Drawing.PointF p2)
        {
            object[] args = new object[] {
                c,
                w,
                p1,
                p2};
            object _ret_val = m_privateObject.Invoke("Line", new System.Type[] {
                    typeof(global::System.Drawing.Color),
                    typeof(int),
                    typeof(global::System.Drawing.PointF),
                    typeof(global::System.Drawing.PointF)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Line(int w, global::System.Drawing.PointF p1, global::System.Drawing.PointF p2)
        {
            object[] args = new object[] {
                w,
                p1,
                p2};
            object _ret_val = m_privateObject.Invoke("Line", new System.Type[] {
                    typeof(int),
                    typeof(global::System.Drawing.PointF),
                    typeof(global::System.Drawing.PointF)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Line(global::System.Drawing.PointF p1, global::System.Drawing.PointF p2)
        {
            object[] args = new object[] {
                p1,
                p2};
            object _ret_val = m_privateObject.Invoke("Line", new System.Type[] {
                    typeof(global::System.Drawing.PointF),
                    typeof(global::System.Drawing.PointF)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Pset(global::System.Drawing.Color c, float w, float x, float y)
        {
            object[] args = new object[] {
                c,
                w,
                x,
                y};
            object _ret_val = m_privateObject.Invoke("Pset", new System.Type[] {
                    typeof(global::System.Drawing.Color),
                    typeof(float),
                    typeof(float),
                    typeof(float)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Pset(float w, float x, float y)
        {
            object[] args = new object[] {
                w,
                x,
                y};
            object _ret_val = m_privateObject.Invoke("Pset", new System.Type[] {
                    typeof(float),
                    typeof(float),
                    typeof(float)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor Pset(float x, float y)
        {
            object[] args = new object[] {
                x,
                y};
            object _ret_val = m_privateObject.Invoke("Pset", new System.Type[] {
                    typeof(float),
                    typeof(float)}, args);
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
            if ((_ret_val != null))
            {
                _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
            }
            global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
            return ret;
        }

        internal global::System.Drawing.SizeF Write(string Text, string FontName, int FontSize, global::System.Drawing.Color c, float w, float x, float y)
        {
            object[] args = new object[] {
                Text,
                FontName,
                FontSize,
                c,
                w,
                x,
                y};
            global::System.Drawing.SizeF ret = ((global::System.Drawing.SizeF)(m_privateObject.Invoke("Write", new System.Type[] {
                    typeof(string),
                    typeof(string),
                    typeof(int),
                    typeof(global::System.Drawing.Color),
                    typeof(float),
                    typeof(float),
                    typeof(float)}, args)));
            return ret;
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw+CoordinateMode");

        internal BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor(object target) :
            base(target, m_privateType)
        {
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor Absolute
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("Absolute");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor ret = _ret;
                return ret;
            }
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor Relative
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("Relative");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_CoordinateModeAccessor ret = _ret;
                return ret;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw+FormBounds");

        internal BlueLogic_SDelta_Core_TextDelta_FormsDraw_FormBoundsAccessor(object target) :
            base(target, m_privateType)
        {
        }

        internal float xMin
        {
            get
            {
                float ret = ((float)(m_privateObject.GetField("xMin")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("xMin", value);
            }
        }

        internal float yMin
        {
            get
            {
                float ret = ((float)(m_privateObject.GetField("yMin")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("yMin", value);
            }
        }

        internal float xMax
        {
            get
            {
                float ret = ((float)(m_privateObject.GetField("xMax")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("xMax", value);
            }
        }

        internal float yMax
        {
            get
            {
                float ret = ((float)(m_privateObject.GetField("yMax")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("yMax", value);
            }
        }

        internal static global::System.ValueType CreatePrivate()
        {
            Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw+FormBounds", new object[0]);
            return ((global::System.ValueType)(priv_obj.Target));
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("BlueLogic.SDelta.Core", "BlueLogic.SDelta.Core.TextDelta.FormsDraw+DrawFeedback");

        internal BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(object target) :
            base(target, m_privateType)
        {
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor N_A
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("N_A");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
                return ret;
            }
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor AOK
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("AOK");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
                return ret;
            }
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ERR
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("ERR");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
                return ret;
            }
        }

        internal static global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor OUT
        {
            get
            {
                object _ret_val = m_privateType.GetStaticField("OUT");
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor _ret = null;
                if ((_ret_val != null))
                {
                    _ret = new global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor(_ret_val);
                }
                global::MatthiasToolbox.Test.BlueLogic_SDelta_Core_TextDelta_FormsDraw_DrawFeedbackAccessor ret = _ret;
                return ret;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_SlidingStreamWindowAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Utilities.IO.SlidingStreamWindow));

        internal BlueLogic_SDelta_Core_SlidingStreamWindowAccessor(global::MatthiasToolbox.Utilities.IO.SlidingStreamWindow target)
            :
                base(target, m_privateType)
        {
        }

        internal global::System.IO.Stream inputStream
        {
            get
            {
                global::System.IO.Stream ret = ((global::System.IO.Stream)(m_privateObject.GetField("inputStream")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("inputStream", value);
            }
        }

        internal int currentIndex
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("currentIndex")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("currentIndex", value);
            }
        }

        internal int currentSize
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("currentSize")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("currentSize", value);
            }
        }

        internal byte[] readBuffer
        {
            get
            {
                byte[] ret = ((byte[])(m_privateObject.GetField("readBuffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("readBuffer", value);
            }
        }

        internal byte[] inputBuffer
        {
            get
            {
                byte[] ret = ((byte[])(m_privateObject.GetField("inputBuffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("inputBuffer", value);
            }
        }

        internal byte[] outputBuffer
        {
            get
            {
                byte[] ret = ((byte[])(m_privateObject.GetField("outputBuffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("outputBuffer", value);
            }
        }

        internal byte[] tempBuffer
        {
            get
            {
                byte[] ret = ((byte[])(m_privateObject.GetField("tempBuffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("tempBuffer", value);
            }
        }

        internal int windowSize
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("windowSize")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("windowSize", value);
            }
        }

        internal int blocksToBuffer
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("blocksToBuffer")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("blocksToBuffer", value);
            }
        }

        internal bool endReached
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetField("endReached")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("endReached", value);
            }
        }

        internal bool finished
        {
            get
            {
                bool ret = ((bool)(m_privateObject.GetField("finished")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("finished", value);
            }
        }

        internal byte[] GetNextWindow()
        {
            object[] args = new object[0];
            byte[] ret = ((byte[])(m_privateObject.Invoke("GetNextWindow", new System.Type[0], args)));
            return ret;
        }

        internal void UpdateBuffer()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("UpdateBuffer", new System.Type[0], args);
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_ConverterAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Delta.Utilities.Converter));

        internal BlueLogic_SDelta_Core_ConverterAccessor() :
            base(m_privateType)
        {
        }

        internal static object ConvertByInterface(global::System.IConvertible source, global::System.Type targetType, global::System.IFormatProvider formatter)
        {
            object[] args = new object[] {
                source,
                targetType,
                formatter};
            object ret = ((object)(m_privateType.InvokeStatic("ConvertByInterface", new System.Type[] {
                    typeof(global::System.IConvertible),
                    typeof(global::System.Type),
                    typeof(global::System.IFormatProvider)}, args)));
            return ret;
        }
    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_MyersTextDiffAccessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Delta.Diff.MyersDiff));

        internal BlueLogic_SDelta_Core_MyersTextDiffAccessor(global::MatthiasToolbox.Delta.Diff.MyersDiff target) :
            base(target, m_privateType)
        {
        }

        internal static int M
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("M")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("M", value);
            }
        }

        internal static int N
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("N")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("N", value);
            }
        }

        internal static int oM
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("oM")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("oM", value);
            }
        }

        internal static int oN
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("oN")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("oN", value);
            }
        }

        internal static int fwdOffset
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("fwdOffset")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("fwdOffset", value);
            }
        }

        internal static int bckOffset
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("bckOffset")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("bckOffset", value);
            }
        }

        internal static int srcLen
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("srcLen")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("srcLen", value);
            }
        }

        internal static int trgLen
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("trgLen")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("trgLen", value);
            }
        }

        internal static bool odd
        {
            get
            {
                bool ret = ((bool)(m_privateType.GetStaticField("odd")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("odd", value);
            }
        }

        internal static int maxD
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("maxD")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("maxD", value);
            }
        }

        internal static int maxMem
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("maxMem")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("maxMem", value);
            }
        }

        internal static int fwdK
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("fwdK")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("fwdK", value);
            }
        }

        internal static int bacK
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("bacK")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("bacK", value);
            }
        }

        internal static int[] vFwd
        {
            get
            {
                int[] ret = ((int[])(m_privateType.GetStaticField("vFwd")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("vFwd", value);
            }
        }

        internal static int[] vBck
        {
            get
            {
                int[] ret = ((int[])(m_privateType.GetStaticField("vBck")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("vBck", value);
            }
        }

        internal static int kFwdBegin
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("kFwdBegin")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("kFwdBegin", value);
            }
        }

        internal static int kFwdEnd
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("kFwdEnd")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("kFwdEnd", value);
            }
        }

        internal static int kBckBegin
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("kBckBegin")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("kBckBegin", value);
            }
        }

        internal static int kBckEnd
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("kBckEnd")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("kBckEnd", value);
            }
        }

        internal static int tmpX
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("tmpX")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("tmpX", value);
            }
        }

        internal static int tmpY
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("tmpY")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("tmpY", value);
            }
        }

        internal int x
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("x")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("x", value);
            }
        }

        internal int y
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("y")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("y", value);
            }
        }

        internal string[] tmpLines1
        {
            get
            {
                string[] ret = ((string[])(m_privateObject.GetField("tmpLines1")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("tmpLines1", value);
            }
        }

        internal string[] tmpLines2
        {
            get
            {
                string[] ret = ((string[])(m_privateObject.GetField("tmpLines2")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("tmpLines2", value);
            }
        }

        internal int[] Indices1
        {
            get
            {
                int[] ret = ((int[])(m_privateObject.GetField("Indices1")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("Indices1", value);
            }
        }

        internal int[] Indices2
        {
            get
            {
                int[] ret = ((int[])(m_privateObject.GetField("Indices2")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("Indices2", value);
            }
        }

        internal bool[] modFlags1
        {
            get
            {
                bool[] ret = ((bool[])(m_privateObject.GetField("modFlags1")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("modFlags1", value);
            }
        }

        internal bool[] modFlags2
        {
            get
            {
                bool[] ret = ((bool[])(m_privateObject.GetField("modFlags2")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("modFlags2", value);
            }
        }

        internal void findMiddleSnake(int[] sourceData, int sourceStart, int sourceEnd, int[] targetData, int targetStart, int targetEnd)
        {
            object[] args = new object[] {
                sourceData,
                sourceStart,
                sourceEnd,
                targetData,
                targetStart,
                targetEnd};
            m_privateObject.Invoke("findMiddleSnake", new System.Type[] {
                    typeof(int).MakeArrayType(),
                    typeof(int),
                    typeof(int),
                    typeof(int).MakeArrayType(),
                    typeof(int),
                    typeof(int)}, args);
        }

        internal void recurse(int[] DataA, int LowerA, int UpperA, int[] DataB, int LowerB, int UpperB)
        {
            object[] args = new object[] {
                DataA,
                LowerA,
                UpperA,
                DataB,
                LowerB,
                UpperB};
            m_privateObject.Invoke("recurse", new System.Type[] {
                    typeof(int).MakeArrayType(),
                    typeof(int),
                    typeof(int),
                    typeof(int).MakeArrayType(),
                    typeof(int),
                    typeof(int)}, args);
        }

        internal void mergeCodes(bool trimSpace)
        {
            object[] args = new object[] {
                trimSpace};
            m_privateObject.Invoke("mergeCodes", new System.Type[] {
                    typeof(bool)}, args);
        }

        internal void makeScript()
        {
            object[] args = new object[0];
            m_privateObject.Invoke("makeScript", new System.Type[0], args);
        }

    }

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
    public class BlueLogic_SDelta_Core_Cryptography_Adler32Accessor : BaseAccessor
    {

        protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::MatthiasToolbox.Cryptography.Checksums.Adler32));

        internal BlueLogic_SDelta_Core_Cryptography_Adler32Accessor(global::MatthiasToolbox.Cryptography.Checksums.Adler32 target) :
            base(target, m_privateType)
        {
        }

        internal int blockSize
        {
            get
            {
                int ret = ((int)(m_privateObject.GetField("blockSize")));
                return ret;
            }
            set
            {
                m_privateObject.SetField("blockSize", value);
            }
        }

        internal static ulong modulo
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("modulo")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("modulo", value);
            }
        }

        internal static int moduloDelay
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("moduloDelay")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("moduloDelay", value);
            }
        }

        internal static ulong s1
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("s1")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("s1", value);
            }
        }

        internal static ulong s2
        {
            get
            {
                ulong ret = ((ulong)(m_privateType.GetStaticField("s2")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("s2", value);
            }
        }

        internal static int i
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("i")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("i", value);
            }
        }

        internal static int k
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("k")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("k", value);
            }
        }

        internal static int adr
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("adr")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("adr", value);
            }
        }

        internal static int len
        {
            get
            {
                int ret = ((int)(m_privateType.GetStaticField("len")));
                return ret;
            }
            set
            {
                m_privateType.SetStaticField("len", value);
            }
        }

        internal static ulong adler32(ulong adler, byte[] buf)
        {
            object[] args = new object[] {
                adler,
                buf};
            ulong ret = ((ulong)(m_privateType.InvokeStatic("adler32", new System.Type[] {
                    typeof(ulong),
                    typeof(byte).MakeArrayType()}, args)));
            return ret;
        }
    }
}